version: '3'

services:
  master:
    image: mysql:5.7
    container_name: mysql-repl_master
    volumes:
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  slave:
    image: mysql:5.7
    container_name: mysql-repl_slave
    volumes:
      - ./slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    links:
      - master
